### ISSUE TITLE
No capability to check unique together fields

### ISSUE THREAD

**Issue by panjiyudasetya** [senseobservationsystems/drf-model-serializer#4]
When a data model has unique together fields, the serializer fails to validate them. It is because, unlike a [`model.full_clean()`](https://github.com/django/django/blob/b9ba85a7ce582f4821a21119a6c130dacab496c4/django/db/models/base.py#L1204) that calls `validate_unique` by default, `model.clean()` didn't do it. So we have to add it to the validate method as well.

**Comment by stargazer** [comment]
The reason we didn't add `validate_unique` in the validation of our custom serializer class, is because unique constraints are database-level constraints. So as long as they are defined on the model, they are guaranteed to work. In addition to that, they are bulletproof and don't suffer from the race conditions that regular validation suffers from.

**Comment by panjiyudasetya** [comment]
Hmm.. okay, I'll close this issue then.
